---
# Dependabot configuration to keep our packages up to date
# Docs: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:
  # Update Ruby gems with Bundler
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    reviewers:
      - jekyll/plugin-core
    # Only update the gems specified in the given file
    file-path: "ruby/gems.rb"

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    reviewers:
      - "jekyll/plugin-core"
    # Only update the workflows specified in the given file
    file-path: ".github/workflows/action.yml"
