# .rubocop.yml

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-jekyll

inherit_gem:
  rubocop-jekyll: .rubocop_jekyll.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - docs/**/*
    - script/**/*
    - test/**/*

