#!/usr/bin/env ruby

# frozen_string_literal: true

STDOUT.sync = true

require_relative "../lib/jekyll-import"
require_relative "../lib/jekyll-import/version"
require_relative "jekyll/commands/import"
require "mercenary"

Mercenary.program(:jekyll_import) do |p|
  p.version JekyllImport::VERSION
  p.description "Import from various blogs to Jekyll format."
  p.syntax "jekyll-import <blog_engine> [options]"

  # Create all the subcommands for the importers.
  JekyllImport.add_importer_commands(p)

  p.action do |args, _|
    if args.empty?
      Jekyll.logger.error "An importer subcommand is required."
      puts p
      abort
    else
      subcommand = args.first
      unless p.has_command? subcommand
        Jekyll.logger.abort_with "fatal: 'jekyll-import #{args.first}'" \
          " could not be found. Make sure you have the required importer gem installed."
      end
    end
  end
end
