---
title: "jekyll-import: Import your old & busted site to Jekyll"
url: https://import.jekyllrb.com
highlighter: rouge
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
repository: https://github.com/jekyll/jekyll-import
latest_release: 0.14.0

collections:
  docs:
    output: true
    permalink: /docs/:path/
  importers:
    output: true
    permalink: /importers/:path/

